"""Update event model with new fields and tags

Revision ID: 217509ad52b8
Revises: 
Create Date: 2025-06-03 16:42:51.002847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '217509ad52b8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_event_tag_id'), 'event_tag', ['id'], unique=False)
    op.create_table('event_tags',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['event_tag.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'tag_id')
    )
    op.add_column('event', sa.Column('start_date', sa.DateTime(timezone=True), nullable=False))
    op.add_column('event', sa.Column('end_date', sa.DateTime(timezone=True), nullable=False))
    op.add_column('event', sa.Column('format', sa.Enum('in_person', 'virtual', 'hybrid', name='eventformatenum'), nullable=True))
    op.add_column('event', sa.Column('cover_image', sa.String(), nullable=True))
    op.add_column('event', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('event', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('event', 'event_date')
    op.drop_column('event', 'is_online')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('is_online', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('event_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('event', 'updated_at')
    op.drop_column('event', 'created_at')
    op.drop_column('event', 'cover_image')
    op.drop_column('event', 'format')
    op.drop_column('event', 'end_date')
    op.drop_column('event', 'start_date')
    op.drop_table('event_tags')
    op.drop_index(op.f('ix_event_tag_id'), table_name='event_tag')
    op.drop_table('event_tag')
    # ### end Alembic commands ###
