"""add author_username to Script

Revision ID: cb3c9767aa9e
Revises: 59fae945517a
Create Date: 2025-06-07 21:02:28.133769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb3c9767aa9e'
down_revision: Union[str, None] = '59fae945517a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scripts', sa.Column('author_username', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scripts', 'author_username')
    # ### end Alembic commands ###
